// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_MP.Models;

#nullable disable

namespace WebApi_MP.Migrations
{
    [DbContext(typeof(MarketPlace2Context))]
    [Migration("20250529031526_InicialConTablas")]
    partial class InicialConTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi_MP.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreCat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCat");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3213E83FF2637565");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("WebApi_MP.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("PrecioUnitario")
                        .HasColumnType("int")
                        .HasColumnName("precioUnitario");

                    b.Property<string>("ProductoRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("productoRef");

                    b.Property<int>("Subtotal")
                        .HasColumnType("int")
                        .HasColumnName("subtotal");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("ventaId");

                    b.HasKey("Id")
                        .HasName("PK__DetalleV__3213E83FBD2FA682");

                    b.HasIndex("ProductoRef");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("WebApi_MP.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Estados__3214EC0719B39456");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("WebApi_MP.Models.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Doc")
                        .HasColumnType("int")
                        .HasColumnName("doc");

                    b.Property<DateOnly>("FechaAgregado")
                        .HasColumnType("date")
                        .HasColumnName("fechaAgregado");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("referencia");

                    b.HasKey("Id")
                        .HasName("PK__Favorito__3213E83F6AD3D323");

                    b.HasIndex("Doc");

                    b.HasIndex("Referencia");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("WebApi_MP.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageableId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imageable_id");

                    b.Property<string>("ImageableType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("imageable_type");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ruta");

                    b.HasKey("Id")
                        .HasName("PK__Fotos__3213E83F1219B9A5");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("WebApi_MP.Models.Producto", b =>
                {
                    b.Property<string>("Referencia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("referencia");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("estadoId");

                    b.Property<string>("NombrePro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombrePro");

                    b.Property<int>("Precio")
                        .HasColumnType("int")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<int>("SubCategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("subCategoriaId");

                    b.Property<int>("UniMedId")
                        .HasColumnType("int")
                        .HasColumnName("uniMedId");

                    b.HasKey("Referencia")
                        .HasName("PK__Producto__85C4EB32A30EE0D0");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("SubCategoriaId");

                    b.HasIndex("UniMedId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("WebApi_MP.Models.Promocione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Descuento")
                        .HasColumnType("int")
                        .HasColumnName("descuento");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("estadoId");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("referencia");

                    b.HasKey("Id")
                        .HasName("PK__Promocio__3213E83FCA392F73");

                    b.HasIndex("EstadoId");

                    b.HasIndex("Referencia");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("WebApi_MP.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreRol");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3213E83FE6FA2C28");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebApi_MP.Models.SubCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoriaId");

                    b.Property<string>("CategoriaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSubCat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreSubCat");

                    b.HasKey("Id")
                        .HasName("PK__SubCateg__3213E83F8AB6F876");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("WebApi_MP.Models.UnidadesMedidum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUniMed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreUniMed");

                    b.HasKey("Id")
                        .HasName("PK__Unidades__3213E83F3DB53722");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("WebApi_MP.Models.UserRole", b =>
                {
                    b.Property<int>("Doc")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Doc", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("WebApi_MP.Models.Usuario", b =>
                {
                    b.Property<int>("Doc")
                        .HasColumnType("int")
                        .HasColumnName("doc");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pass");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("telefono");

                    b.HasKey("Doc")
                        .HasName("PK__Usuarios__D87601412868CB95");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApi_MP.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Doc")
                        .HasColumnType("int")
                        .HasColumnName("doc");

                    b.Property<int?>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estadoId");

                    b.Property<DateOnly>("FechaVenta")
                        .HasColumnType("date")
                        .HasColumnName("fechaVenta");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__Ventas__3213E83F65B4EFD4");

                    b.HasIndex("Doc");

                    b.HasIndex("EstadoId");

                    b.ToTable("Ventas", t =>
                        {
                            t.HasTrigger("DescontarStock");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebApi_MP.Models.VentasDetallada", b =>
                {
                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(101)
                        .IsUnicode(false)
                        .HasColumnType("varchar(101)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("FechaVenta")
                        .HasColumnType("date")
                        .HasColumnName("fechaVenta");

                    b.Property<int>("PrecioUnitario")
                        .HasColumnType("int")
                        .HasColumnName("precioUnitario");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Subtotal")
                        .HasColumnType("int")
                        .HasColumnName("subtotal");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("VentasDetalladas", (string)null);
                });

            modelBuilder.Entity("WebApi_MP.Models.DetalleVenta", b =>
                {
                    b.HasOne("WebApi_MP.Models.Producto", "ProductoRefNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("ProductoRef")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__produ__52593CB8");

                    b.HasOne("WebApi_MP.Models.Venta", "Venta")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__venta__534D60F1");

                    b.Navigation("ProductoRefNavigation");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("WebApi_MP.Models.Favorito", b =>
                {
                    b.HasOne("WebApi_MP.Models.Usuario", "DocNavigation")
                        .WithMany("Favoritos")
                        .HasForeignKey("Doc")
                        .IsRequired()
                        .HasConstraintName("FK__Favoritos__doc__693CA210");

                    b.HasOne("WebApi_MP.Models.Producto", "ReferenciaNavigation")
                        .WithMany("Favoritos")
                        .HasForeignKey("Referencia")
                        .IsRequired()
                        .HasConstraintName("FK__Favoritos__refer__6A30C649");

                    b.Navigation("DocNavigation");

                    b.Navigation("ReferenciaNavigation");
                });

            modelBuilder.Entity("WebApi_MP.Models.Producto", b =>
                {
                    b.HasOne("WebApi_MP.Models.Categoria", null)
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("WebApi_MP.Models.Estado", "Estado")
                        .WithMany("Productos")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK__Productos__estad__48CFD27E");

                    b.HasOne("WebApi_MP.Models.SubCategoria", "SubCategoria")
                        .WithMany("Productos")
                        .HasForeignKey("SubCategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__subCat__49C3F6B7");

                    b.HasOne("WebApi_MP.Models.UnidadesMedidum", "UniMed")
                        .WithMany("Productos")
                        .HasForeignKey("UniMedId")
                        .IsRequired()
                        .HasConstraintName("FK__Productos__uniMe__4AB81AF0");

                    b.Navigation("Estado");

                    b.Navigation("SubCategoria");

                    b.Navigation("UniMed");
                });

            modelBuilder.Entity("WebApi_MP.Models.Promocione", b =>
                {
                    b.HasOne("WebApi_MP.Models.Estado", "Estado")
                        .WithMany("Promociones")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Promocion__estad__6E01572D");

                    b.HasOne("WebApi_MP.Models.Producto", "ReferenciaNavigation")
                        .WithMany("Promociones")
                        .HasForeignKey("Referencia")
                        .IsRequired()
                        .HasConstraintName("FK__Promocion__refer__6D0D32F4");

                    b.Navigation("Estado");

                    b.Navigation("ReferenciaNavigation");
                });

            modelBuilder.Entity("WebApi_MP.Models.SubCategoria", b =>
                {
                    b.HasOne("WebApi_MP.Models.Categoria", "Categoria")
                        .WithMany("SubCategoria")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__SubCatego__categ__4316F928");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebApi_MP.Models.UserRole", b =>
                {
                    b.HasOne("WebApi_MP.Models.Usuario", "Usuario")
                        .WithMany("UserRoles")
                        .HasForeignKey("Doc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Usuarios");

                    b.HasOne("WebApi_MP.Models.Role", "Rol")
                        .WithMany("UserRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApi_MP.Models.Venta", b =>
                {
                    b.HasOne("WebApi_MP.Models.Usuario", "DocNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("Doc")
                        .IsRequired()
                        .HasConstraintName("FK__Ventas__doc__4F7CD00D");

                    b.HasOne("WebApi_MP.Models.Estado", "Estado")
                        .WithMany("Venta")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK__Ventas__estadoId__4E88ABD4");

                    b.Navigation("DocNavigation");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("WebApi_MP.Models.Categoria", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("WebApi_MP.Models.Estado", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Promociones");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("WebApi_MP.Models.Producto", b =>
                {
                    b.Navigation("DetalleVenta");

                    b.Navigation("Favoritos");

                    b.Navigation("Promociones");
                });

            modelBuilder.Entity("WebApi_MP.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebApi_MP.Models.SubCategoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("WebApi_MP.Models.UnidadesMedidum", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("WebApi_MP.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("UserRoles");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("WebApi_MP.Models.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
